### ISSUE TITLE
Change background layer

### ISSUE THREAD

**Issue by ahennr** [terrestris/SolrHeatmap#10]
Background layer must be replaced by a gray one with higher contrast.

For example:
- [OWS terrestris gray](https://ows.terrestris.de/dienste.html#openstreetmap-wms)
  ![OWS terrestris gray sample](https://ows.terrestris.de/_images/osmwms2.jpg)
- [Stamen (Toner)](http://maps.stamen.com/toner)
- Mapbox (as used in [MapLoom](http://maploom.terranodo.io/)): Is there an API key needed?

Which one should we use @ingenieroariel

**Comment by annarieger** [comment]
Can this issue be closed now, @ingenieroariel?

**Comment by ingenieroariel** [comment]
Yes, please.
