### ISSUE TITLE
Redline fixes

### ISSUE THREAD

**Issue by ingenieroariel** [terrestris/SolrHeatmap#13]
![real-time_billlion_geotweets_2_-_root_dataverse](https://cloud.githubusercontent.com/assets/54999/15928058/c4b04ca2-2e12-11e6-879b-fe152c8a2d10.png)

**Comment by ingenieroariel** [comment]
For the shade of gray: http://dataverse.org

<img width="81" alt="screen shot 2016-06-09 at 7 25 07 am" src="https://cloud.githubusercontent.com/assets/54999/15928173/59db9b2e-2e13-11e6-8b4b-7d9017da0606.png">

**Comment by raprasad** [comment]
Thanks for changes @annarieger

**Comment by annarieger** [comment]
You're welcome, @raprasad :wink: 

Can this issue be closed now?

**Comment by raprasad** [comment]
Yes.  please close it
